export const formatCurrency = (amount) => {
  return new Intl.NumberFormat('uz-UZ', {
    style: 'currency',
    currency: 'UZS',
    minimumFractionDigits: 0,
  }).format(amount || 0);
};

export const generateJobsheet = (
  debtorInfo,
  visitStartTime,
  outcome,
  customerContacted,
  paymentAmount,
  nextAction,
  notes,
  location,
  capturedPhoto
) => {
  const visitDuration = Math.round((new Date() - visitStartTime) / (1000 * 60)); // minutes

  return {
    visitDate: new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }),
    debtor: debtorInfo,
    officer: 'Field Officer', // This should come from auth context
    visitDuration: `${visitDuration} minutes`,
    outcome,
    customerContacted,
    paymentReceived: paymentAmount ? parseFloat(paymentAmount) : 0,
    nextAction,
    remarks: notes,
    location: location
      ? {
          lat: location.latitude.toFixed(6),
          lng: location.longitude.toFixed(6),
        }
      : null,
    photoTaken: !!capturedPhoto,
  };
};

export const formatJobsheetText = (jobsheet, formatCurrency) => {
  return `
FIELD VISIT REPORT
==================

Date: ${jobsheet.visitDate}
Officer: ${jobsheet.officer}
Duration: ${jobsheet.visitDuration}

DEBTOR INFORMATION:
------------------
Name: ${jobsheet.debtor.name}
PINFL: ${jobsheet.debtor.pinfl}
Address: ${jobsheet.debtor.address}
Phone: ${jobsheet.debtor.phone}
Total Debt: ${formatCurrency(jobsheet.debtor.totalAmount)}
Remaining: ${formatCurrency(jobsheet.debtor.remainingAmount)}

VISIT DETAILS:
--------------
Outcome: ${jobsheet.outcome || 'Not specified'}
Customer Contacted: ${jobsheet.customerContacted ? 'Yes' : 'No'}
Payment Received: ${formatCurrency(jobsheet.paymentReceived)}
Photo Evidence: ${jobsheet.photoTaken ? 'Yes' : 'No'}

NEXT ACTIONS:
-------------
${jobsheet.nextAction || 'None specified'}

REMARKS:
--------
${jobsheet.remarks || 'No additional remarks'}

LOCATION:
---------
${jobsheet.location ? `Lat: ${jobsheet.location.lat}, Lng: ${jobsheet.location.lng}` : 'Location not captured'}

Generated by CollPro Field App
  `;
};
